### ISSUE TITLE
Still developed?

### ISSUE THREAD

**Issue by proepkes** [NixInteractive/RTS-Tutorial-Code#1]
Thanks for your tutorials. I saw that you thought about working on a rts pathfinding solution. Is there any news about this?

**Comment by NixInteractive** [comment]
Sorry for the late reply. I haven't found a reliable/smooth pathfinding solution just yet. I've been putting it off until I got the multi-select system working reliably. Now that I have I'm going to play around with formation movement and pathfinding to see if I can get a reliable system.
